// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Primary design header
//
// This header should be included by all source files instantiating the design.
// The class here is then constructed to instantiate the design.
// See the Verilator manual for examples.

#ifndef _VMLMC_SIM_H_
#define _VMLMC_SIM_H_  // guard

#include "verilated.h"

//==========

class VMlmc_Sim__Syms;
class VMlmc_Sim_VerilatedVcd;


//----------

VL_MODULE(VMlmc_Sim) {
  public:
    
    // PORTS
    // The application code writes and reads these signals to
    // propagate new values into/out from the Verilated model.
    VL_IN8(clk,0,0);
    VL_IN8(reset,0,0);
    VL_OUT8(emif_emif_data_writeEnable,0,0);
    VL_IN8(emif_emif_cs,0,0);
    VL_IN8(emif_emif_we,0,0);
    VL_IN8(emif_emif_oe,0,0);
    VL_OUT8(ad5544_A_AD5544_CS,0,0);
    VL_OUT8(ad5544_A_AD5544_LDAC,0,0);
    VL_OUT8(ad5544_A_AD5544_MSB,0,0);
    VL_OUT8(ad5544_A_AD5544_RS,0,0);
    VL_OUT8(ad5544_A_AD5544_SCLK,0,0);
    VL_OUT8(ad5544_A_AD5544_SDIN,0,0);
    VL_OUT8(ad5544_B_AD5544_CS,0,0);
    VL_OUT8(ad5544_B_AD5544_LDAC,0,0);
    VL_OUT8(ad5544_B_AD5544_MSB,0,0);
    VL_OUT8(ad5544_B_AD5544_RS,0,0);
    VL_OUT8(ad5544_B_AD5544_SCLK,0,0);
    VL_OUT8(ad5544_B_AD5544_SDIN,0,0);
    VL_OUT8(bissc_master_enc_clk,0,0);
    VL_IN8(bissc_master_enc_data,0,0);
    VL_IN8(bissc_slave_0_enc_clk,0,0);
    VL_OUT8(bissc_slave_0_enc_data,0,0);
    VL_IN8(bissc_slave_1_enc_clk,0,0);
    VL_OUT8(bissc_slave_1_enc_data,0,0);
    VL_IN8(bissc_slave_2_enc_clk,0,0);
    VL_OUT8(bissc_slave_2_enc_data,0,0);
    VL_IN8(bissc_slave_3_enc_clk,0,0);
    VL_OUT8(bissc_slave_3_enc_data,0,0);
    VL_IN8(bissc_slave_4_enc_clk,0,0);
    VL_OUT8(bissc_slave_4_enc_data,0,0);
    VL_IN8(bissc_slave_5_enc_clk,0,0);
    VL_OUT8(bissc_slave_5_enc_data,0,0);
    VL_IN8(bissc_slave_6_enc_clk,0,0);
    VL_OUT8(bissc_slave_6_enc_data,0,0);
    VL_IN8(bissc_slave_7_enc_clk,0,0);
    VL_OUT8(bissc_slave_7_enc_data,0,0);
    VL_IN8(bissc_slave_8_enc_clk,0,0);
    VL_OUT8(bissc_slave_8_enc_data,0,0);
    VL_IN8(bissc_slave_9_enc_clk,0,0);
    VL_OUT8(bissc_slave_9_enc_data,0,0);
    VL_IN8(bissc_slave_10_enc_clk,0,0);
    VL_OUT8(bissc_slave_10_enc_data,0,0);
    VL_IN8(bissc_slave_11_enc_clk,0,0);
    VL_OUT8(bissc_slave_11_enc_data,0,0);
    VL_IN8(bissc_slave_12_enc_clk,0,0);
    VL_OUT8(bissc_slave_12_enc_data,0,0);
    VL_IN8(bissc_slave_13_enc_clk,0,0);
    VL_OUT8(bissc_slave_13_enc_data,0,0);
    VL_IN8(bissc_slave_14_enc_clk,0,0);
    VL_OUT8(bissc_slave_14_enc_data,0,0);
    VL_IN8(bissc_slave_15_enc_clk,0,0);
    VL_OUT8(bissc_slave_15_enc_data,0,0);
    VL_IN8(bissc_slave_16_enc_clk,0,0);
    VL_OUT8(bissc_slave_16_enc_data,0,0);
    VL_IN8(bissc_slave_17_enc_clk,0,0);
    VL_OUT8(bissc_slave_17_enc_data,0,0);
    VL_IN8(bissc_slave_18_enc_clk,0,0);
    VL_OUT8(bissc_slave_18_enc_data,0,0);
    VL_IN8(bissc_slave_19_enc_clk,0,0);
    VL_OUT8(bissc_slave_19_enc_data,0,0);
    VL_IN8(bissc_slave_20_enc_clk,0,0);
    VL_OUT8(bissc_slave_20_enc_data,0,0);
    VL_IN8(bissc_slave_21_enc_clk,0,0);
    VL_OUT8(bissc_slave_21_enc_data,0,0);
    VL_IN8(bissc_slave_22_enc_clk,0,0);
    VL_OUT8(bissc_slave_22_enc_data,0,0);
    VL_IN8(bissc_slave_23_enc_clk,0,0);
    VL_OUT8(bissc_slave_23_enc_data,0,0);
    VL_OUT8(led,0,0);
    VL_IN16(emif_emif_data_read,15,0);
    VL_OUT16(emif_emif_data_write,15,0);
    VL_OUT16(gpioA,11,0);
    VL_OUT16(gpioB,11,0);
    VL_IN(emif_emif_addr,18,0);
    
    // LOCAL SIGNALS
    // Internals; generally not touched by application code
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ Mlmc_Sim__DOT__area_ad5544_1_Ctrl__DOT__area_ad5544_ctrl__DOT__clk_out;
        CData/*0:0*/ Mlmc_Sim__DOT__area_ad5544_2_Ctrl__DOT__area_ad5544_ctrl__DOT__clk_out;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_ctrl__DOT__area_bissc_ctrl__DOT__clk_out;
        CData/*0:0*/ Mlmc_Sim__DOT__area_emif_interface_apb_PENABLE;
        CData/*0:0*/ Mlmc_Sim__DOT__area_emif_interface_apb_PWRITE;
        CData/*0:0*/ Mlmc_Sim__DOT__area_ad5544_triger_ad5544_tri;
        CData/*0:0*/ Mlmc_Sim__DOT__apb_decoder_io_input_PREADY;
        CData/*0:0*/ Mlmc_Sim__DOT__apb_decoder_io_input_PSLVERROR;
        CData/*5:0*/ Mlmc_Sim__DOT__apb_decoder_io_output_PSEL;
        CData/*0:0*/ Mlmc_Sim__DOT__area_ledtemp;
        CData/*0:0*/ Mlmc_Sim__DOT__area_counter_willClear;
        CData/*0:0*/ Mlmc_Sim__DOT__area_emif_interface__DOT__penable;
        CData/*0:0*/ Mlmc_Sim__DOT__area_emif_interface__DOT__penable_regNext;
        CData/*0:0*/ Mlmc_Sim__DOT__area_ad5544_triger__DOT__area_temp;
        CData/*0:0*/ Mlmc_Sim__DOT__area_ad5544_triger__DOT__when_AD5544_l91;
        CData/*0:0*/ Mlmc_Sim__DOT__area_ad5544_triger__DOT__area_temp_delay_1;
        CData/*0:0*/ Mlmc_Sim__DOT__area_ad5544_triger__DOT__area_temp_delay_2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_ad5544_triger__DOT__area_temp_delay_3;
        CData/*0:0*/ Mlmc_Sim__DOT__area_ad5544_1_Ctrl__DOT__area_ad5544_ctrl_AD5544_CS;
        CData/*0:0*/ Mlmc_Sim__DOT__area_ad5544_1_Ctrl__DOT__area_ad5544_ctrl_AD5544_LDAC;
        CData/*0:0*/ Mlmc_Sim__DOT__area_ad5544_1_Ctrl__DOT__area_ad5544_ctrl_AD5544_RS;
        CData/*0:0*/ Mlmc_Sim__DOT__area_ad5544_1_Ctrl__DOT__area_ad5544_ctrl_AD5544_SCLK;
        CData/*0:0*/ Mlmc_Sim__DOT__area_ad5544_1_Ctrl__DOT__area_ad5544_ctrl_AD5544_SDIN;
        CData/*0:0*/ Mlmc_Sim__DOT__area_ad5544_1_Ctrl__DOT__area_ctrl_doWrite;
        CData/*3:0*/ Mlmc_Sim__DOT__area_ad5544_1_Ctrl__DOT__area_ad5544_ctrl__DOT__channel;
        CData/*6:0*/ Mlmc_Sim__DOT__area_ad5544_1_Ctrl__DOT__area_ad5544_ctrl__DOT__curr_state;
        CData/*6:0*/ Mlmc_Sim__DOT__area_ad5544_1_Ctrl__DOT__area_ad5544_ctrl__DOT__next_state;
        CData/*3:0*/ Mlmc_Sim__DOT__area_ad5544_1_Ctrl__DOT__area_ad5544_ctrl__DOT__clk_dvidecnt;
        CData/*0:0*/ Mlmc_Sim__DOT__area_ad5544_1_Ctrl__DOT__area_ad5544_ctrl__DOT__ad5544_trig_reg1;
        CData/*0:0*/ Mlmc_Sim__DOT__area_ad5544_1_Ctrl__DOT__area_ad5544_ctrl__DOT__ad5544_trig_reg2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_ad5544_2_Ctrl__DOT__area_ad5544_ctrl_AD5544_CS;
        CData/*0:0*/ Mlmc_Sim__DOT__area_ad5544_2_Ctrl__DOT__area_ad5544_ctrl_AD5544_LDAC;
        CData/*0:0*/ Mlmc_Sim__DOT__area_ad5544_2_Ctrl__DOT__area_ad5544_ctrl_AD5544_RS;
        CData/*0:0*/ Mlmc_Sim__DOT__area_ad5544_2_Ctrl__DOT__area_ad5544_ctrl_AD5544_SCLK;
        CData/*0:0*/ Mlmc_Sim__DOT__area_ad5544_2_Ctrl__DOT__area_ad5544_ctrl_AD5544_SDIN;
        CData/*0:0*/ Mlmc_Sim__DOT__area_ad5544_2_Ctrl__DOT__area_ctrl_doWrite;
        CData/*3:0*/ Mlmc_Sim__DOT__area_ad5544_2_Ctrl__DOT__area_ad5544_ctrl__DOT__channel;
        CData/*6:0*/ Mlmc_Sim__DOT__area_ad5544_2_Ctrl__DOT__area_ad5544_ctrl__DOT__curr_state;
        CData/*6:0*/ Mlmc_Sim__DOT__area_ad5544_2_Ctrl__DOT__area_ad5544_ctrl__DOT__next_state;
        CData/*3:0*/ Mlmc_Sim__DOT__area_ad5544_2_Ctrl__DOT__area_ad5544_ctrl__DOT__clk_dvidecnt;
        CData/*0:0*/ Mlmc_Sim__DOT__area_ad5544_2_Ctrl__DOT__area_ad5544_ctrl__DOT__ad5544_trig_reg1;
        CData/*0:0*/ Mlmc_Sim__DOT__area_ad5544_2_Ctrl__DOT__area_ad5544_ctrl__DOT__ad5544_trig_reg2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_ctrl__DOT__area_bissc_ctrl_enc_clk;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_ctrl__DOT__area_bissc_ctrl_erro_flag;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_ctrl__DOT__area_bissc_ctrl_warn_flag;
        CData/*1:0*/ Mlmc_Sim__DOT__area_bissc_ctrl__DOT__area_bissc_ctrl__DOT__start_flag;
        CData/*7:0*/ Mlmc_Sim__DOT__area_bissc_ctrl__DOT__area_bissc_ctrl__DOT__Next_State;
        CData/*7:0*/ Mlmc_Sim__DOT__area_bissc_ctrl__DOT__area_bissc_ctrl__DOT__Curr_State;
        CData/*3:0*/ Mlmc_Sim__DOT__area_bissc_ctrl__DOT__area_bissc_ctrl__DOT__clk_dvidecnt;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_ctrl__DOT__area_bissc_ctrl__DOT__ENC_SLO_1reg;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_ctrl__DOT__area_bissc_ctrl__DOT__ENC_SLO_2reg;
        CData/*0:0*/ Mlmc_Sim__DOT__area_apb_gpio__DOT__ctrl_doWrite;
        CData/*0:0*/ Mlmc_Sim__DOT__area_apb_ram__DOT__stream_fifo_io_pop_ready;
        CData/*0:0*/ Mlmc_Sim__DOT__area_apb_ram__DOT__ctrl_doWrite;
        CData/*0:0*/ Mlmc_Sim__DOT__area_apb_ram__DOT___zz_io_push_valid;
        CData/*0:0*/ Mlmc_Sim__DOT__area_apb_ram__DOT__stream_fifo_io_flush_driver;
        CData/*0:0*/ Mlmc_Sim__DOT__area_apb_ram__DOT__stream_fifo__DOT___zz_1;
        CData/*0:0*/ Mlmc_Sim__DOT__area_apb_ram__DOT__stream_fifo__DOT__logic_pushPtr_willIncrement;
        CData/*0:0*/ Mlmc_Sim__DOT__area_apb_ram__DOT__stream_fifo__DOT__logic_pushPtr_willClear;
        CData/*0:0*/ Mlmc_Sim__DOT__area_apb_ram__DOT__stream_fifo__DOT__logic_popPtr_willIncrement;
        CData/*0:0*/ Mlmc_Sim__DOT__area_apb_ram__DOT__stream_fifo__DOT__logic_popPtr_willClear;
        CData/*0:0*/ Mlmc_Sim__DOT__area_apb_ram__DOT__stream_fifo__DOT__logic_ptrMatch;
        CData/*0:0*/ Mlmc_Sim__DOT__area_apb_ram__DOT__stream_fifo__DOT__logic_risingOccupancy;
        CData/*0:0*/ Mlmc_Sim__DOT__area_apb_ram__DOT__stream_fifo__DOT__logic_pushing;
    };
    struct {
        CData/*0:0*/ Mlmc_Sim__DOT__area_apb_ram__DOT__stream_fifo__DOT__logic_popping;
        CData/*0:0*/ Mlmc_Sim__DOT__area_apb_ram__DOT__stream_fifo__DOT__logic_full;
        CData/*0:0*/ Mlmc_Sim__DOT__area_apb_ram__DOT__stream_fifo__DOT___zz_io_pop_valid;
        CData/*0:0*/ Mlmc_Sim__DOT__apb_decoder__DOT__when_Apb3Decoder_l88;
        CData/*2:0*/ Mlmc_Sim__DOT__apb3Router_1__DOT__selIndex;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_0__DOT___zz_bisscdata_2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_0__DOT__bisscdata;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_0__DOT__clkrise_cnt;
        CData/*7:0*/ Mlmc_Sim__DOT__area_bissc_slave_0__DOT__timeout_cnt;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_0__DOT__fsm_wantStart;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_0__DOT__fsm_stateReg;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_0__DOT__fsm_stateNext;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_0__DOT__when_BissC_l33;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_0__DOT__when_BissC_l45;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_0__DOT__when_BissC_l57;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_0__DOT__s_bissc_enc_clk_regNext_5;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_0__DOT__when_BissC_l84;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_0__DOT__when_BissC_l87;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_1__DOT___zz_bisscdata_2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_1__DOT__bisscdata;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_1__DOT__clkrise_cnt;
        CData/*7:0*/ Mlmc_Sim__DOT__area_bissc_slave_1__DOT__timeout_cnt;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_1__DOT__fsm_wantStart;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_1__DOT__fsm_stateReg;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_1__DOT__fsm_stateNext;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_1__DOT__when_BissC_l33;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_1__DOT__when_BissC_l45;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_1__DOT__when_BissC_l57;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_1__DOT__s_bissc_enc_clk_regNext_5;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_1__DOT__when_BissC_l84;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_1__DOT__when_BissC_l87;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_2__DOT___zz_bisscdata_2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_2__DOT__bisscdata;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_2__DOT__clkrise_cnt;
        CData/*7:0*/ Mlmc_Sim__DOT__area_bissc_slave_2__DOT__timeout_cnt;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_2__DOT__fsm_wantStart;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_2__DOT__fsm_stateReg;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_2__DOT__fsm_stateNext;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_2__DOT__when_BissC_l33;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_2__DOT__when_BissC_l45;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_2__DOT__when_BissC_l57;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_2__DOT__s_bissc_enc_clk_regNext_5;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_2__DOT__when_BissC_l84;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_2__DOT__when_BissC_l87;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_3__DOT___zz_bisscdata_2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_3__DOT__bisscdata;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_3__DOT__clkrise_cnt;
        CData/*7:0*/ Mlmc_Sim__DOT__area_bissc_slave_3__DOT__timeout_cnt;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_3__DOT__fsm_wantStart;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_3__DOT__fsm_stateReg;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_3__DOT__fsm_stateNext;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_3__DOT__when_BissC_l33;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_3__DOT__when_BissC_l45;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_3__DOT__when_BissC_l57;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_3__DOT__s_bissc_enc_clk_regNext_5;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_3__DOT__when_BissC_l84;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_3__DOT__when_BissC_l87;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_4__DOT___zz_bisscdata_2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_4__DOT__bisscdata;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_4__DOT__clkrise_cnt;
        CData/*7:0*/ Mlmc_Sim__DOT__area_bissc_slave_4__DOT__timeout_cnt;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_4__DOT__fsm_wantStart;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_4__DOT__fsm_stateReg;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_4__DOT__fsm_stateNext;
    };
    struct {
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_4__DOT__when_BissC_l33;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_4__DOT__when_BissC_l45;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_4__DOT__when_BissC_l57;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_4__DOT__s_bissc_enc_clk_regNext_5;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_4__DOT__when_BissC_l84;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_4__DOT__when_BissC_l87;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_5__DOT___zz_bisscdata_2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_5__DOT__bisscdata;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_5__DOT__clkrise_cnt;
        CData/*7:0*/ Mlmc_Sim__DOT__area_bissc_slave_5__DOT__timeout_cnt;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_5__DOT__fsm_wantStart;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_5__DOT__fsm_stateReg;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_5__DOT__fsm_stateNext;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_5__DOT__when_BissC_l33;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_5__DOT__when_BissC_l45;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_5__DOT__when_BissC_l57;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_5__DOT__s_bissc_enc_clk_regNext_5;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_5__DOT__when_BissC_l84;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_5__DOT__when_BissC_l87;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_6__DOT___zz_bisscdata_2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_6__DOT__bisscdata;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_6__DOT__clkrise_cnt;
        CData/*7:0*/ Mlmc_Sim__DOT__area_bissc_slave_6__DOT__timeout_cnt;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_6__DOT__fsm_wantStart;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_6__DOT__fsm_stateReg;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_6__DOT__fsm_stateNext;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_6__DOT__when_BissC_l33;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_6__DOT__when_BissC_l45;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_6__DOT__when_BissC_l57;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_6__DOT__s_bissc_enc_clk_regNext_5;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_6__DOT__when_BissC_l84;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_6__DOT__when_BissC_l87;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_7__DOT___zz_bisscdata_2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_7__DOT__bisscdata;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_7__DOT__clkrise_cnt;
        CData/*7:0*/ Mlmc_Sim__DOT__area_bissc_slave_7__DOT__timeout_cnt;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_7__DOT__fsm_wantStart;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_7__DOT__fsm_stateReg;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_7__DOT__fsm_stateNext;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_7__DOT__when_BissC_l33;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_7__DOT__when_BissC_l45;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_7__DOT__when_BissC_l57;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_7__DOT__s_bissc_enc_clk_regNext_5;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_7__DOT__when_BissC_l84;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_7__DOT__when_BissC_l87;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_8__DOT___zz_bisscdata_2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_8__DOT__bisscdata;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_8__DOT__clkrise_cnt;
        CData/*7:0*/ Mlmc_Sim__DOT__area_bissc_slave_8__DOT__timeout_cnt;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_8__DOT__fsm_wantStart;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_8__DOT__fsm_stateReg;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_8__DOT__fsm_stateNext;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_8__DOT__when_BissC_l33;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_8__DOT__when_BissC_l45;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_8__DOT__when_BissC_l57;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_8__DOT__s_bissc_enc_clk_regNext_5;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_8__DOT__when_BissC_l84;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_8__DOT__when_BissC_l87;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_9__DOT___zz_bisscdata_2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_9__DOT__bisscdata;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_9__DOT__clkrise_cnt;
        CData/*7:0*/ Mlmc_Sim__DOT__area_bissc_slave_9__DOT__timeout_cnt;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_9__DOT__fsm_wantStart;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_9__DOT__fsm_stateReg;
    };
    struct {
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_9__DOT__fsm_stateNext;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_9__DOT__when_BissC_l33;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_9__DOT__when_BissC_l45;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_9__DOT__when_BissC_l57;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_9__DOT__s_bissc_enc_clk_regNext_5;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_9__DOT__when_BissC_l84;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_9__DOT__when_BissC_l87;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_10__DOT___zz_bisscdata_2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_10__DOT__bisscdata;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_10__DOT__clkrise_cnt;
        CData/*7:0*/ Mlmc_Sim__DOT__area_bissc_slave_10__DOT__timeout_cnt;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_10__DOT__fsm_wantStart;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_10__DOT__fsm_stateReg;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_10__DOT__fsm_stateNext;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_10__DOT__when_BissC_l33;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_10__DOT__when_BissC_l45;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_10__DOT__when_BissC_l57;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_10__DOT__s_bissc_enc_clk_regNext_5;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_10__DOT__when_BissC_l84;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_10__DOT__when_BissC_l87;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_11__DOT___zz_bisscdata_2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_11__DOT__bisscdata;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_11__DOT__clkrise_cnt;
        CData/*7:0*/ Mlmc_Sim__DOT__area_bissc_slave_11__DOT__timeout_cnt;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_11__DOT__fsm_wantStart;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_11__DOT__fsm_stateReg;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_11__DOT__fsm_stateNext;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_11__DOT__when_BissC_l33;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_11__DOT__when_BissC_l45;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_11__DOT__when_BissC_l57;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_11__DOT__s_bissc_enc_clk_regNext_5;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_11__DOT__when_BissC_l84;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_11__DOT__when_BissC_l87;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_12__DOT___zz_bisscdata_2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_12__DOT__bisscdata;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_12__DOT__clkrise_cnt;
        CData/*7:0*/ Mlmc_Sim__DOT__area_bissc_slave_12__DOT__timeout_cnt;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_12__DOT__fsm_wantStart;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_12__DOT__fsm_stateReg;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_12__DOT__fsm_stateNext;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_12__DOT__when_BissC_l33;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_12__DOT__when_BissC_l45;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_12__DOT__when_BissC_l57;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_12__DOT__s_bissc_enc_clk_regNext_5;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_12__DOT__when_BissC_l84;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_12__DOT__when_BissC_l87;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_13__DOT___zz_bisscdata_2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_13__DOT__bisscdata;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_13__DOT__clkrise_cnt;
        CData/*7:0*/ Mlmc_Sim__DOT__area_bissc_slave_13__DOT__timeout_cnt;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_13__DOT__fsm_wantStart;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_13__DOT__fsm_stateReg;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_13__DOT__fsm_stateNext;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_13__DOT__when_BissC_l33;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_13__DOT__when_BissC_l45;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_13__DOT__when_BissC_l57;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_13__DOT__s_bissc_enc_clk_regNext_5;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_13__DOT__when_BissC_l84;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_13__DOT__when_BissC_l87;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_14__DOT___zz_bisscdata_2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_14__DOT__bisscdata;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_14__DOT__clkrise_cnt;
        CData/*7:0*/ Mlmc_Sim__DOT__area_bissc_slave_14__DOT__timeout_cnt;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_14__DOT__fsm_wantStart;
    };
    struct {
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_14__DOT__fsm_stateReg;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_14__DOT__fsm_stateNext;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_14__DOT__when_BissC_l33;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_14__DOT__when_BissC_l45;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_14__DOT__when_BissC_l57;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_14__DOT__s_bissc_enc_clk_regNext_5;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_14__DOT__when_BissC_l84;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_14__DOT__when_BissC_l87;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_15__DOT___zz_bisscdata_2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_15__DOT__bisscdata;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_15__DOT__clkrise_cnt;
        CData/*7:0*/ Mlmc_Sim__DOT__area_bissc_slave_15__DOT__timeout_cnt;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_15__DOT__fsm_wantStart;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_15__DOT__fsm_stateReg;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_15__DOT__fsm_stateNext;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_15__DOT__when_BissC_l33;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_15__DOT__when_BissC_l45;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_15__DOT__when_BissC_l57;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_15__DOT__s_bissc_enc_clk_regNext_5;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_15__DOT__when_BissC_l84;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_15__DOT__when_BissC_l87;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_16__DOT___zz_bisscdata_2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_16__DOT__bisscdata;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_16__DOT__clkrise_cnt;
        CData/*7:0*/ Mlmc_Sim__DOT__area_bissc_slave_16__DOT__timeout_cnt;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_16__DOT__fsm_wantStart;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_16__DOT__fsm_stateReg;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_16__DOT__fsm_stateNext;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_16__DOT__when_BissC_l33;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_16__DOT__when_BissC_l45;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_16__DOT__when_BissC_l57;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_16__DOT__s_bissc_enc_clk_regNext_5;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_16__DOT__when_BissC_l84;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_16__DOT__when_BissC_l87;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_17__DOT___zz_bisscdata_2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_17__DOT__bisscdata;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_17__DOT__clkrise_cnt;
        CData/*7:0*/ Mlmc_Sim__DOT__area_bissc_slave_17__DOT__timeout_cnt;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_17__DOT__fsm_wantStart;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_17__DOT__fsm_stateReg;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_17__DOT__fsm_stateNext;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_17__DOT__when_BissC_l33;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_17__DOT__when_BissC_l45;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_17__DOT__when_BissC_l57;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_17__DOT__s_bissc_enc_clk_regNext_5;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_17__DOT__when_BissC_l84;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_17__DOT__when_BissC_l87;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_18__DOT___zz_bisscdata_2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_18__DOT__bisscdata;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_18__DOT__clkrise_cnt;
        CData/*7:0*/ Mlmc_Sim__DOT__area_bissc_slave_18__DOT__timeout_cnt;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_18__DOT__fsm_wantStart;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_18__DOT__fsm_stateReg;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_18__DOT__fsm_stateNext;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_18__DOT__when_BissC_l33;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_18__DOT__when_BissC_l45;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_18__DOT__when_BissC_l57;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_18__DOT__s_bissc_enc_clk_regNext_5;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_18__DOT__when_BissC_l84;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_18__DOT__when_BissC_l87;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_19__DOT___zz_bisscdata_2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_19__DOT__bisscdata;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_19__DOT__clkrise_cnt;
        CData/*7:0*/ Mlmc_Sim__DOT__area_bissc_slave_19__DOT__timeout_cnt;
    };
    struct {
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_19__DOT__fsm_wantStart;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_19__DOT__fsm_stateReg;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_19__DOT__fsm_stateNext;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_19__DOT__when_BissC_l33;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_19__DOT__when_BissC_l45;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_19__DOT__when_BissC_l57;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_19__DOT__s_bissc_enc_clk_regNext_5;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_19__DOT__when_BissC_l84;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_19__DOT__when_BissC_l87;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_20__DOT___zz_bisscdata_2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_20__DOT__bisscdata;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_20__DOT__clkrise_cnt;
        CData/*7:0*/ Mlmc_Sim__DOT__area_bissc_slave_20__DOT__timeout_cnt;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_20__DOT__fsm_wantStart;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_20__DOT__fsm_stateReg;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_20__DOT__fsm_stateNext;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_20__DOT__when_BissC_l33;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_20__DOT__when_BissC_l45;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_20__DOT__when_BissC_l57;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_20__DOT__s_bissc_enc_clk_regNext_5;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_20__DOT__when_BissC_l84;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_20__DOT__when_BissC_l87;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_21__DOT___zz_bisscdata_2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_21__DOT__bisscdata;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_21__DOT__clkrise_cnt;
        CData/*7:0*/ Mlmc_Sim__DOT__area_bissc_slave_21__DOT__timeout_cnt;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_21__DOT__fsm_wantStart;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_21__DOT__fsm_stateReg;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_21__DOT__fsm_stateNext;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_21__DOT__when_BissC_l33;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_21__DOT__when_BissC_l45;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_21__DOT__when_BissC_l57;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_21__DOT__s_bissc_enc_clk_regNext_5;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_21__DOT__when_BissC_l84;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_21__DOT__when_BissC_l87;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_22__DOT___zz_bisscdata_2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_22__DOT__bisscdata;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_22__DOT__clkrise_cnt;
        CData/*7:0*/ Mlmc_Sim__DOT__area_bissc_slave_22__DOT__timeout_cnt;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_22__DOT__fsm_wantStart;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_22__DOT__fsm_stateReg;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_22__DOT__fsm_stateNext;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_22__DOT__when_BissC_l33;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_22__DOT__when_BissC_l45;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_22__DOT__when_BissC_l57;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_22__DOT__s_bissc_enc_clk_regNext_5;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_22__DOT__when_BissC_l84;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_22__DOT__when_BissC_l87;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_23__DOT___zz_bisscdata_2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_23__DOT__bisscdata;
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_slave_23__DOT__clkrise_cnt;
        CData/*7:0*/ Mlmc_Sim__DOT__area_bissc_slave_23__DOT__timeout_cnt;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_23__DOT__fsm_wantStart;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_23__DOT__fsm_stateReg;
        CData/*2:0*/ Mlmc_Sim__DOT__area_bissc_slave_23__DOT__fsm_stateNext;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_23__DOT__when_BissC_l33;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_23__DOT__when_BissC_l45;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_23__DOT__when_BissC_l57;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_23__DOT__s_bissc_enc_clk_regNext_5;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_23__DOT__when_BissC_l84;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_23__DOT__when_BissC_l87;
        SData/*15:0*/ Mlmc_Sim__DOT__area_ad5544_triger_apb_PRDATA;
        SData/*15:0*/ Mlmc_Sim__DOT__area_ad5544_1_Ctrl_apb_PRDATA;
        SData/*15:0*/ Mlmc_Sim__DOT__area_ad5544_2_Ctrl_apb_PRDATA;
    };
    struct {
        SData/*15:0*/ Mlmc_Sim__DOT__area_bissc_ctrl_apb_PRDATA;
        SData/*15:0*/ Mlmc_Sim__DOT__area_apb_gpio_io_apb_PRDATA;
        SData/*15:0*/ Mlmc_Sim__DOT__area_apb_ram_apb_PRDATA;
        SData/*15:0*/ Mlmc_Sim__DOT__area_emif_interface__DOT__rd_data_temp;
        SData/*15:0*/ Mlmc_Sim__DOT__area_ad5544_1_Ctrl__DOT__area_ad5544_ctrl_AD5544_DATA_IN1_driver;
        SData/*15:0*/ Mlmc_Sim__DOT__area_ad5544_1_Ctrl__DOT__area_ad5544_ctrl_AD5544_DATA_IN2_driver;
        SData/*15:0*/ Mlmc_Sim__DOT__area_ad5544_1_Ctrl__DOT__area_ad5544_ctrl_AD5544_DATA_IN3_driver;
        SData/*15:0*/ Mlmc_Sim__DOT__area_ad5544_1_Ctrl__DOT__area_ad5544_ctrl_AD5544_DATA_IN4_driver;
        SData/*9:0*/ Mlmc_Sim__DOT__area_ad5544_1_Ctrl__DOT__area_ad5544_ctrl__DOT__cnt;
        SData/*15:0*/ Mlmc_Sim__DOT__area_ad5544_2_Ctrl__DOT__area_ad5544_ctrl_AD5544_DATA_IN1_driver;
        SData/*15:0*/ Mlmc_Sim__DOT__area_ad5544_2_Ctrl__DOT__area_ad5544_ctrl_AD5544_DATA_IN2_driver;
        SData/*15:0*/ Mlmc_Sim__DOT__area_ad5544_2_Ctrl__DOT__area_ad5544_ctrl_AD5544_DATA_IN3_driver;
        SData/*15:0*/ Mlmc_Sim__DOT__area_ad5544_2_Ctrl__DOT__area_ad5544_ctrl_AD5544_DATA_IN4_driver;
        SData/*9:0*/ Mlmc_Sim__DOT__area_ad5544_2_Ctrl__DOT__area_ad5544_ctrl__DOT__cnt;
        SData/*15:0*/ Mlmc_Sim__DOT__area_bissc_ctrl__DOT__area_bissc_status_reg;
        SData/*11:0*/ Mlmc_Sim__DOT__area_bissc_ctrl__DOT__area_bissc_ctrl__DOT__CNT;
        SData/*11:0*/ Mlmc_Sim__DOT__area_bissc_ctrl__DOT__area_bissc_ctrl__DOT__DATA_CNT;
        SData/*11:0*/ Mlmc_Sim__DOT__area_apb_gpio__DOT__io_gpioA_driver;
        SData/*11:0*/ Mlmc_Sim__DOT__area_apb_gpio__DOT__io_gpioB_driver;
        SData/*15:0*/ Mlmc_Sim__DOT__area_apb_ram__DOT__stream_fifo__DOT___zz_logic_ram_port0;
        SData/*8:0*/ Mlmc_Sim__DOT__area_apb_ram__DOT__stream_fifo__DOT__logic_pushPtr_valueNext;
        SData/*8:0*/ Mlmc_Sim__DOT__area_apb_ram__DOT__stream_fifo__DOT__logic_pushPtr_value;
        SData/*8:0*/ Mlmc_Sim__DOT__area_apb_ram__DOT__stream_fifo__DOT__logic_popPtr_valueNext;
        SData/*8:0*/ Mlmc_Sim__DOT__area_apb_ram__DOT__stream_fifo__DOT__logic_popPtr_value;
        SData/*15:0*/ Mlmc_Sim__DOT__apb3Router_1__DOT___zz_io_input_PRDATA;
        IData/*25:0*/ Mlmc_Sim__DOT__area_counter_valueNext;
        IData/*25:0*/ Mlmc_Sim__DOT__area_counter_value;
        IData/*17:0*/ Mlmc_Sim__DOT__area_ad5544_1_Ctrl__DOT__area_ad5544_ctrl__DOT__AD5544_SDIN_reg;
        IData/*17:0*/ Mlmc_Sim__DOT__area_ad5544_2_Ctrl__DOT__area_ad5544_ctrl__DOT__AD5544_SDIN_reg;
        IData/*31:0*/ Mlmc_Sim__DOT__area_bissc_ctrl__DOT__area_bissc_ctrl_enc_position_out;
        IData/*31:0*/ Mlmc_Sim__DOT__area_bissc_ctrl__DOT__area_bissc_pos_reg;
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_0__DOT__fsm_stateReg_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_0__DOT__fsm_stateNext_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_1__DOT__fsm_stateReg_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_1__DOT__fsm_stateNext_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_2__DOT__fsm_stateReg_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_2__DOT__fsm_stateNext_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_3__DOT__fsm_stateReg_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_3__DOT__fsm_stateNext_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_4__DOT__fsm_stateReg_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_4__DOT__fsm_stateNext_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_5__DOT__fsm_stateReg_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_5__DOT__fsm_stateNext_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_6__DOT__fsm_stateReg_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_6__DOT__fsm_stateNext_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_7__DOT__fsm_stateReg_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_7__DOT__fsm_stateNext_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_8__DOT__fsm_stateReg_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_8__DOT__fsm_stateNext_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_9__DOT__fsm_stateReg_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_9__DOT__fsm_stateNext_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_10__DOT__fsm_stateReg_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_10__DOT__fsm_stateNext_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_11__DOT__fsm_stateReg_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_11__DOT__fsm_stateNext_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_12__DOT__fsm_stateReg_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_12__DOT__fsm_stateNext_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_13__DOT__fsm_stateReg_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_13__DOT__fsm_stateNext_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_14__DOT__fsm_stateReg_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_14__DOT__fsm_stateNext_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_15__DOT__fsm_stateReg_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_15__DOT__fsm_stateNext_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_16__DOT__fsm_stateReg_string[3];
    };
    struct {
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_16__DOT__fsm_stateNext_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_17__DOT__fsm_stateReg_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_17__DOT__fsm_stateNext_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_18__DOT__fsm_stateReg_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_18__DOT__fsm_stateNext_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_19__DOT__fsm_stateReg_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_19__DOT__fsm_stateNext_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_20__DOT__fsm_stateReg_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_20__DOT__fsm_stateNext_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_21__DOT__fsm_stateReg_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_21__DOT__fsm_stateNext_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_22__DOT__fsm_stateReg_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_22__DOT__fsm_stateNext_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_23__DOT__fsm_stateReg_string[3];
        WData/*79:0*/ Mlmc_Sim__DOT__area_bissc_slave_23__DOT__fsm_stateNext_string[3];
        QData/*40:0*/ Mlmc_Sim__DOT__area_bissc_ctrl__DOT__area_bissc_ctrl_enc_position_all;
        QData/*40:0*/ Mlmc_Sim__DOT__area_bissc_slave_0__DOT__postion_reg;
        QData/*40:0*/ Mlmc_Sim__DOT__area_bissc_slave_1__DOT__postion_reg;
        QData/*40:0*/ Mlmc_Sim__DOT__area_bissc_slave_2__DOT__postion_reg;
        QData/*40:0*/ Mlmc_Sim__DOT__area_bissc_slave_3__DOT__postion_reg;
        QData/*40:0*/ Mlmc_Sim__DOT__area_bissc_slave_4__DOT__postion_reg;
        QData/*40:0*/ Mlmc_Sim__DOT__area_bissc_slave_5__DOT__postion_reg;
        QData/*40:0*/ Mlmc_Sim__DOT__area_bissc_slave_6__DOT__postion_reg;
        QData/*40:0*/ Mlmc_Sim__DOT__area_bissc_slave_7__DOT__postion_reg;
        QData/*40:0*/ Mlmc_Sim__DOT__area_bissc_slave_8__DOT__postion_reg;
        QData/*40:0*/ Mlmc_Sim__DOT__area_bissc_slave_9__DOT__postion_reg;
        QData/*40:0*/ Mlmc_Sim__DOT__area_bissc_slave_10__DOT__postion_reg;
        QData/*40:0*/ Mlmc_Sim__DOT__area_bissc_slave_11__DOT__postion_reg;
        QData/*40:0*/ Mlmc_Sim__DOT__area_bissc_slave_12__DOT__postion_reg;
        QData/*40:0*/ Mlmc_Sim__DOT__area_bissc_slave_13__DOT__postion_reg;
        QData/*40:0*/ Mlmc_Sim__DOT__area_bissc_slave_14__DOT__postion_reg;
        QData/*40:0*/ Mlmc_Sim__DOT__area_bissc_slave_15__DOT__postion_reg;
        QData/*40:0*/ Mlmc_Sim__DOT__area_bissc_slave_16__DOT__postion_reg;
        QData/*40:0*/ Mlmc_Sim__DOT__area_bissc_slave_17__DOT__postion_reg;
        QData/*40:0*/ Mlmc_Sim__DOT__area_bissc_slave_18__DOT__postion_reg;
        QData/*40:0*/ Mlmc_Sim__DOT__area_bissc_slave_19__DOT__postion_reg;
        QData/*40:0*/ Mlmc_Sim__DOT__area_bissc_slave_20__DOT__postion_reg;
        QData/*40:0*/ Mlmc_Sim__DOT__area_bissc_slave_21__DOT__postion_reg;
        QData/*40:0*/ Mlmc_Sim__DOT__area_bissc_slave_22__DOT__postion_reg;
        QData/*40:0*/ Mlmc_Sim__DOT__area_bissc_slave_23__DOT__postion_reg;
        SData/*15:0*/ Mlmc_Sim__DOT__area_apb_ram__DOT__stream_fifo__DOT__logic_ram[512];
    };
    
    // LOCAL VARIABLES
    // Internals; generally not touched by application code
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*5:0*/ Mlmc_Sim__DOT__area_bissc_ctrl__DOT____Vcellout__area_bissc_ctrl__crc_flag;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_0__DOT____Vxrand2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_0__DOT____Vxrand1;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_1__DOT____Vxrand2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_1__DOT____Vxrand1;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_2__DOT____Vxrand2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_2__DOT____Vxrand1;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_3__DOT____Vxrand2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_3__DOT____Vxrand1;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_4__DOT____Vxrand2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_4__DOT____Vxrand1;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_5__DOT____Vxrand2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_5__DOT____Vxrand1;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_6__DOT____Vxrand2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_6__DOT____Vxrand1;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_7__DOT____Vxrand2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_7__DOT____Vxrand1;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_8__DOT____Vxrand2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_8__DOT____Vxrand1;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_9__DOT____Vxrand2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_9__DOT____Vxrand1;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_10__DOT____Vxrand2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_10__DOT____Vxrand1;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_11__DOT____Vxrand2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_11__DOT____Vxrand1;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_12__DOT____Vxrand2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_12__DOT____Vxrand1;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_13__DOT____Vxrand2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_13__DOT____Vxrand1;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_14__DOT____Vxrand2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_14__DOT____Vxrand1;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_15__DOT____Vxrand2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_15__DOT____Vxrand1;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_16__DOT____Vxrand2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_16__DOT____Vxrand1;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_17__DOT____Vxrand2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_17__DOT____Vxrand1;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_18__DOT____Vxrand2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_18__DOT____Vxrand1;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_19__DOT____Vxrand2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_19__DOT____Vxrand1;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_20__DOT____Vxrand2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_20__DOT____Vxrand1;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_21__DOT____Vxrand2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_21__DOT____Vxrand1;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_22__DOT____Vxrand2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_22__DOT____Vxrand1;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_23__DOT____Vxrand2;
        CData/*0:0*/ Mlmc_Sim__DOT__area_bissc_slave_23__DOT____Vxrand1;
        CData/*2:0*/ __Vtableidx1;
        CData/*2:0*/ __Vtableidx2;
        CData/*2:0*/ __Vtableidx3;
        CData/*2:0*/ __Vtableidx4;
        CData/*2:0*/ __Vtableidx5;
        CData/*2:0*/ __Vtableidx6;
        CData/*2:0*/ __Vtableidx7;
        CData/*2:0*/ __Vtableidx8;
        CData/*2:0*/ __Vtableidx9;
        CData/*2:0*/ __Vtableidx10;
        CData/*2:0*/ __Vtableidx11;
        CData/*2:0*/ __Vtableidx12;
        CData/*2:0*/ __Vtableidx13;
        CData/*2:0*/ __Vtableidx14;
        CData/*2:0*/ __Vtableidx15;
    };
    struct {
        CData/*2:0*/ __Vtableidx16;
        CData/*2:0*/ __Vtableidx17;
        CData/*2:0*/ __Vtableidx18;
        CData/*2:0*/ __Vtableidx19;
        CData/*2:0*/ __Vtableidx20;
        CData/*2:0*/ __Vtableidx21;
        CData/*2:0*/ __Vtableidx22;
        CData/*2:0*/ __Vtableidx23;
        CData/*2:0*/ __Vtableidx24;
        CData/*2:0*/ __Vtableidx25;
        CData/*2:0*/ __Vtableidx26;
        CData/*2:0*/ __Vtableidx27;
        CData/*2:0*/ __Vtableidx28;
        CData/*2:0*/ __Vtableidx29;
        CData/*2:0*/ __Vtableidx30;
        CData/*2:0*/ __Vtableidx31;
        CData/*2:0*/ __Vtableidx32;
        CData/*2:0*/ __Vtableidx33;
        CData/*2:0*/ __Vtableidx34;
        CData/*2:0*/ __Vtableidx35;
        CData/*2:0*/ __Vtableidx36;
        CData/*2:0*/ __Vtableidx37;
        CData/*2:0*/ __Vtableidx38;
        CData/*2:0*/ __Vtableidx39;
        CData/*2:0*/ __Vtableidx40;
        CData/*2:0*/ __Vtableidx41;
        CData/*2:0*/ __Vtableidx42;
        CData/*2:0*/ __Vtableidx43;
        CData/*2:0*/ __Vtableidx44;
        CData/*2:0*/ __Vtableidx45;
        CData/*2:0*/ __Vtableidx46;
        CData/*2:0*/ __Vtableidx47;
        CData/*2:0*/ __Vtableidx48;
        CData/*2:0*/ __Vtableidx49;
        CData/*2:0*/ __Vtableidx50;
        CData/*2:0*/ __Vtableidx51;
        CData/*2:0*/ __Vtableidx52;
        CData/*2:0*/ __Vtableidx53;
        CData/*2:0*/ __Vtableidx54;
        CData/*2:0*/ __Vtableidx55;
        CData/*2:0*/ __Vtableidx56;
        CData/*2:0*/ __Vtableidx57;
        CData/*2:0*/ __Vtableidx58;
        CData/*2:0*/ __Vtableidx59;
        CData/*2:0*/ __Vtableidx60;
        CData/*2:0*/ __Vtableidx61;
        CData/*2:0*/ __Vtableidx62;
        CData/*2:0*/ __Vtableidx63;
        CData/*2:0*/ __Vtableidx64;
        CData/*2:0*/ __Vtableidx65;
        CData/*2:0*/ __Vtableidx66;
        CData/*2:0*/ __Vtableidx67;
        CData/*2:0*/ __Vtableidx68;
        CData/*2:0*/ __Vtableidx69;
        CData/*2:0*/ __Vtableidx70;
        CData/*2:0*/ __Vtableidx71;
        CData/*2:0*/ __Vtableidx72;
        CData/*0:0*/ __Vdly__Mlmc_Sim__DOT__area_ledtemp;
        CData/*3:0*/ __Vdly__Mlmc_Sim__DOT__area_ad5544_1_Ctrl__DOT__area_ad5544_ctrl__DOT__clk_dvidecnt;
        CData/*0:0*/ __Vdly__Mlmc_Sim__DOT__area_ad5544_1_Ctrl__DOT__area_ad5544_ctrl__DOT__clk_out;
        CData/*3:0*/ __Vdly__Mlmc_Sim__DOT__area_ad5544_2_Ctrl__DOT__area_ad5544_ctrl__DOT__clk_dvidecnt;
        CData/*0:0*/ __Vdly__Mlmc_Sim__DOT__area_ad5544_2_Ctrl__DOT__area_ad5544_ctrl__DOT__clk_out;
        CData/*3:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_ctrl__DOT__area_bissc_ctrl__DOT__clk_dvidecnt;
        CData/*0:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_ctrl__DOT__area_bissc_ctrl__DOT__clk_out;
    };
    struct {
        CData/*5:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_0__DOT__clkrise_cnt;
        CData/*7:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_0__DOT__timeout_cnt;
        CData/*5:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_1__DOT__clkrise_cnt;
        CData/*7:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_1__DOT__timeout_cnt;
        CData/*5:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_2__DOT__clkrise_cnt;
        CData/*7:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_2__DOT__timeout_cnt;
        CData/*5:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_3__DOT__clkrise_cnt;
        CData/*7:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_3__DOT__timeout_cnt;
        CData/*5:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_4__DOT__clkrise_cnt;
        CData/*7:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_4__DOT__timeout_cnt;
        CData/*5:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_5__DOT__clkrise_cnt;
        CData/*7:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_5__DOT__timeout_cnt;
        CData/*5:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_6__DOT__clkrise_cnt;
        CData/*7:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_6__DOT__timeout_cnt;
        CData/*5:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_7__DOT__clkrise_cnt;
        CData/*7:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_7__DOT__timeout_cnt;
        CData/*5:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_8__DOT__clkrise_cnt;
        CData/*7:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_8__DOT__timeout_cnt;
        CData/*5:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_9__DOT__clkrise_cnt;
        CData/*7:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_9__DOT__timeout_cnt;
        CData/*5:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_10__DOT__clkrise_cnt;
        CData/*7:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_10__DOT__timeout_cnt;
        CData/*5:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_11__DOT__clkrise_cnt;
        CData/*7:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_11__DOT__timeout_cnt;
        CData/*5:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_12__DOT__clkrise_cnt;
        CData/*7:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_12__DOT__timeout_cnt;
        CData/*5:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_13__DOT__clkrise_cnt;
        CData/*7:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_13__DOT__timeout_cnt;
        CData/*5:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_14__DOT__clkrise_cnt;
        CData/*7:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_14__DOT__timeout_cnt;
        CData/*5:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_15__DOT__clkrise_cnt;
        CData/*7:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_15__DOT__timeout_cnt;
        CData/*5:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_16__DOT__clkrise_cnt;
        CData/*7:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_16__DOT__timeout_cnt;
        CData/*5:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_17__DOT__clkrise_cnt;
        CData/*7:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_17__DOT__timeout_cnt;
        CData/*5:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_18__DOT__clkrise_cnt;
        CData/*7:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_18__DOT__timeout_cnt;
        CData/*5:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_19__DOT__clkrise_cnt;
        CData/*7:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_19__DOT__timeout_cnt;
        CData/*5:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_20__DOT__clkrise_cnt;
        CData/*7:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_20__DOT__timeout_cnt;
        CData/*5:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_21__DOT__clkrise_cnt;
        CData/*7:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_21__DOT__timeout_cnt;
        CData/*5:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_22__DOT__clkrise_cnt;
        CData/*7:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_22__DOT__timeout_cnt;
        CData/*5:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_23__DOT__clkrise_cnt;
        CData/*7:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_slave_23__DOT__timeout_cnt;
        CData/*3:0*/ __Vdly__Mlmc_Sim__DOT__area_ad5544_1_Ctrl__DOT__area_ad5544_ctrl__DOT__channel;
        CData/*3:0*/ __Vdly__Mlmc_Sim__DOT__area_ad5544_2_Ctrl__DOT__area_ad5544_ctrl__DOT__channel;
        CData/*1:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_ctrl__DOT__area_bissc_ctrl__DOT__start_flag;
        CData/*0:0*/ __VinpClk__TOP__Mlmc_Sim__DOT__area_bissc_ctrl__DOT__area_bissc_ctrl__DOT__clk_out;
        CData/*0:0*/ __VinpClk__TOP__Mlmc_Sim__DOT__area_ad5544_2_Ctrl__DOT__area_ad5544_ctrl__DOT__clk_out;
        CData/*0:0*/ __VinpClk__TOP__Mlmc_Sim__DOT__area_ad5544_1_Ctrl__DOT__area_ad5544_ctrl__DOT__clk_out;
        CData/*0:0*/ __Vclklast__TOP__clk;
        CData/*0:0*/ __Vclklast__TOP__reset;
        CData/*0:0*/ __Vclklast__TOP____VinpClk__TOP__Mlmc_Sim__DOT__area_bissc_ctrl__DOT__area_bissc_ctrl__DOT__clk_out;
        CData/*0:0*/ __Vclklast__TOP____VinpClk__TOP__Mlmc_Sim__DOT__area_ad5544_2_Ctrl__DOT__area_ad5544_ctrl__DOT__clk_out;
        CData/*0:0*/ __Vclklast__TOP____VinpClk__TOP__Mlmc_Sim__DOT__area_ad5544_1_Ctrl__DOT__area_ad5544_ctrl__DOT__clk_out;
        CData/*0:0*/ __Vchglast__TOP__Mlmc_Sim__DOT__area_ad5544_1_Ctrl__DOT__area_ad5544_ctrl__DOT__clk_out;
        CData/*0:0*/ __Vchglast__TOP__Mlmc_Sim__DOT__area_ad5544_2_Ctrl__DOT__area_ad5544_ctrl__DOT__clk_out;
        CData/*0:0*/ __Vchglast__TOP__Mlmc_Sim__DOT__area_bissc_ctrl__DOT__area_bissc_ctrl__DOT__clk_out;
        SData/*9:0*/ __Vdly__Mlmc_Sim__DOT__area_ad5544_1_Ctrl__DOT__area_ad5544_ctrl__DOT__cnt;
        SData/*9:0*/ __Vdly__Mlmc_Sim__DOT__area_ad5544_2_Ctrl__DOT__area_ad5544_ctrl__DOT__cnt;
    };
    struct {
        SData/*11:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_ctrl__DOT__area_bissc_ctrl__DOT__CNT;
        SData/*11:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_ctrl__DOT__area_bissc_ctrl__DOT__DATA_CNT;
        IData/*17:0*/ __Vdly__Mlmc_Sim__DOT__area_ad5544_1_Ctrl__DOT__area_ad5544_ctrl__DOT__AD5544_SDIN_reg;
        IData/*17:0*/ __Vdly__Mlmc_Sim__DOT__area_ad5544_2_Ctrl__DOT__area_ad5544_ctrl__DOT__AD5544_SDIN_reg;
        IData/*31:0*/ __Vm_traceActivity;
        QData/*40:0*/ __Vdly__Mlmc_Sim__DOT__area_bissc_ctrl__DOT__area_bissc_ctrl_enc_position_all;
    };
    static WData/*79:0*/ __Vtable1_Mlmc_Sim__DOT__area_bissc_slave_0__DOT__fsm_stateReg_string[8][3];
    static WData/*79:0*/ __Vtable2_Mlmc_Sim__DOT__area_bissc_slave_0__DOT__fsm_stateNext_string[8][3];
    static CData/*0:0*/ __Vtable3_Mlmc_Sim__DOT__area_bissc_slave_0__DOT__fsm_wantStart[8];
    static WData/*79:0*/ __Vtable4_Mlmc_Sim__DOT__area_bissc_slave_1__DOT__fsm_stateReg_string[8][3];
    static WData/*79:0*/ __Vtable5_Mlmc_Sim__DOT__area_bissc_slave_1__DOT__fsm_stateNext_string[8][3];
    static CData/*0:0*/ __Vtable6_Mlmc_Sim__DOT__area_bissc_slave_1__DOT__fsm_wantStart[8];
    static WData/*79:0*/ __Vtable7_Mlmc_Sim__DOT__area_bissc_slave_2__DOT__fsm_stateReg_string[8][3];
    static WData/*79:0*/ __Vtable8_Mlmc_Sim__DOT__area_bissc_slave_2__DOT__fsm_stateNext_string[8][3];
    static CData/*0:0*/ __Vtable9_Mlmc_Sim__DOT__area_bissc_slave_2__DOT__fsm_wantStart[8];
    static WData/*79:0*/ __Vtable10_Mlmc_Sim__DOT__area_bissc_slave_3__DOT__fsm_stateReg_string[8][3];
    static WData/*79:0*/ __Vtable11_Mlmc_Sim__DOT__area_bissc_slave_3__DOT__fsm_stateNext_string[8][3];
    static CData/*0:0*/ __Vtable12_Mlmc_Sim__DOT__area_bissc_slave_3__DOT__fsm_wantStart[8];
    static WData/*79:0*/ __Vtable13_Mlmc_Sim__DOT__area_bissc_slave_4__DOT__fsm_stateReg_string[8][3];
    static WData/*79:0*/ __Vtable14_Mlmc_Sim__DOT__area_bissc_slave_4__DOT__fsm_stateNext_string[8][3];
    static CData/*0:0*/ __Vtable15_Mlmc_Sim__DOT__area_bissc_slave_4__DOT__fsm_wantStart[8];
    static WData/*79:0*/ __Vtable16_Mlmc_Sim__DOT__area_bissc_slave_5__DOT__fsm_stateReg_string[8][3];
    static WData/*79:0*/ __Vtable17_Mlmc_Sim__DOT__area_bissc_slave_5__DOT__fsm_stateNext_string[8][3];
    static CData/*0:0*/ __Vtable18_Mlmc_Sim__DOT__area_bissc_slave_5__DOT__fsm_wantStart[8];
    static WData/*79:0*/ __Vtable19_Mlmc_Sim__DOT__area_bissc_slave_6__DOT__fsm_stateReg_string[8][3];
    static WData/*79:0*/ __Vtable20_Mlmc_Sim__DOT__area_bissc_slave_6__DOT__fsm_stateNext_string[8][3];
    static CData/*0:0*/ __Vtable21_Mlmc_Sim__DOT__area_bissc_slave_6__DOT__fsm_wantStart[8];
    static WData/*79:0*/ __Vtable22_Mlmc_Sim__DOT__area_bissc_slave_7__DOT__fsm_stateReg_string[8][3];
    static WData/*79:0*/ __Vtable23_Mlmc_Sim__DOT__area_bissc_slave_7__DOT__fsm_stateNext_string[8][3];
    static CData/*0:0*/ __Vtable24_Mlmc_Sim__DOT__area_bissc_slave_7__DOT__fsm_wantStart[8];
    static WData/*79:0*/ __Vtable25_Mlmc_Sim__DOT__area_bissc_slave_8__DOT__fsm_stateReg_string[8][3];
    static WData/*79:0*/ __Vtable26_Mlmc_Sim__DOT__area_bissc_slave_8__DOT__fsm_stateNext_string[8][3];
    static CData/*0:0*/ __Vtable27_Mlmc_Sim__DOT__area_bissc_slave_8__DOT__fsm_wantStart[8];
    static WData/*79:0*/ __Vtable28_Mlmc_Sim__DOT__area_bissc_slave_9__DOT__fsm_stateReg_string[8][3];
    static WData/*79:0*/ __Vtable29_Mlmc_Sim__DOT__area_bissc_slave_9__DOT__fsm_stateNext_string[8][3];
    static CData/*0:0*/ __Vtable30_Mlmc_Sim__DOT__area_bissc_slave_9__DOT__fsm_wantStart[8];
    static WData/*79:0*/ __Vtable31_Mlmc_Sim__DOT__area_bissc_slave_10__DOT__fsm_stateReg_string[8][3];
    static WData/*79:0*/ __Vtable32_Mlmc_Sim__DOT__area_bissc_slave_10__DOT__fsm_stateNext_string[8][3];
    static CData/*0:0*/ __Vtable33_Mlmc_Sim__DOT__area_bissc_slave_10__DOT__fsm_wantStart[8];
    static WData/*79:0*/ __Vtable34_Mlmc_Sim__DOT__area_bissc_slave_11__DOT__fsm_stateReg_string[8][3];
    static WData/*79:0*/ __Vtable35_Mlmc_Sim__DOT__area_bissc_slave_11__DOT__fsm_stateNext_string[8][3];
    static CData/*0:0*/ __Vtable36_Mlmc_Sim__DOT__area_bissc_slave_11__DOT__fsm_wantStart[8];
    static WData/*79:0*/ __Vtable37_Mlmc_Sim__DOT__area_bissc_slave_12__DOT__fsm_stateReg_string[8][3];
    static WData/*79:0*/ __Vtable38_Mlmc_Sim__DOT__area_bissc_slave_12__DOT__fsm_stateNext_string[8][3];
    static CData/*0:0*/ __Vtable39_Mlmc_Sim__DOT__area_bissc_slave_12__DOT__fsm_wantStart[8];
    static WData/*79:0*/ __Vtable40_Mlmc_Sim__DOT__area_bissc_slave_13__DOT__fsm_stateReg_string[8][3];
    static WData/*79:0*/ __Vtable41_Mlmc_Sim__DOT__area_bissc_slave_13__DOT__fsm_stateNext_string[8][3];
    static CData/*0:0*/ __Vtable42_Mlmc_Sim__DOT__area_bissc_slave_13__DOT__fsm_wantStart[8];
    static WData/*79:0*/ __Vtable43_Mlmc_Sim__DOT__area_bissc_slave_14__DOT__fsm_stateReg_string[8][3];
    static WData/*79:0*/ __Vtable44_Mlmc_Sim__DOT__area_bissc_slave_14__DOT__fsm_stateNext_string[8][3];
    static CData/*0:0*/ __Vtable45_Mlmc_Sim__DOT__area_bissc_slave_14__DOT__fsm_wantStart[8];
    static WData/*79:0*/ __Vtable46_Mlmc_Sim__DOT__area_bissc_slave_15__DOT__fsm_stateReg_string[8][3];
    static WData/*79:0*/ __Vtable47_Mlmc_Sim__DOT__area_bissc_slave_15__DOT__fsm_stateNext_string[8][3];
    static CData/*0:0*/ __Vtable48_Mlmc_Sim__DOT__area_bissc_slave_15__DOT__fsm_wantStart[8];
    static WData/*79:0*/ __Vtable49_Mlmc_Sim__DOT__area_bissc_slave_16__DOT__fsm_stateReg_string[8][3];
    static WData/*79:0*/ __Vtable50_Mlmc_Sim__DOT__area_bissc_slave_16__DOT__fsm_stateNext_string[8][3];
    static CData/*0:0*/ __Vtable51_Mlmc_Sim__DOT__area_bissc_slave_16__DOT__fsm_wantStart[8];
    static WData/*79:0*/ __Vtable52_Mlmc_Sim__DOT__area_bissc_slave_17__DOT__fsm_stateReg_string[8][3];
    static WData/*79:0*/ __Vtable53_Mlmc_Sim__DOT__area_bissc_slave_17__DOT__fsm_stateNext_string[8][3];
    static CData/*0:0*/ __Vtable54_Mlmc_Sim__DOT__area_bissc_slave_17__DOT__fsm_wantStart[8];
    static WData/*79:0*/ __Vtable55_Mlmc_Sim__DOT__area_bissc_slave_18__DOT__fsm_stateReg_string[8][3];
    static WData/*79:0*/ __Vtable56_Mlmc_Sim__DOT__area_bissc_slave_18__DOT__fsm_stateNext_string[8][3];
    static CData/*0:0*/ __Vtable57_Mlmc_Sim__DOT__area_bissc_slave_18__DOT__fsm_wantStart[8];
    static WData/*79:0*/ __Vtable58_Mlmc_Sim__DOT__area_bissc_slave_19__DOT__fsm_stateReg_string[8][3];
    static WData/*79:0*/ __Vtable59_Mlmc_Sim__DOT__area_bissc_slave_19__DOT__fsm_stateNext_string[8][3];
    static CData/*0:0*/ __Vtable60_Mlmc_Sim__DOT__area_bissc_slave_19__DOT__fsm_wantStart[8];
    static WData/*79:0*/ __Vtable61_Mlmc_Sim__DOT__area_bissc_slave_20__DOT__fsm_stateReg_string[8][3];
    static WData/*79:0*/ __Vtable62_Mlmc_Sim__DOT__area_bissc_slave_20__DOT__fsm_stateNext_string[8][3];
    static CData/*0:0*/ __Vtable63_Mlmc_Sim__DOT__area_bissc_slave_20__DOT__fsm_wantStart[8];
    static WData/*79:0*/ __Vtable64_Mlmc_Sim__DOT__area_bissc_slave_21__DOT__fsm_stateReg_string[8][3];
    static WData/*79:0*/ __Vtable65_Mlmc_Sim__DOT__area_bissc_slave_21__DOT__fsm_stateNext_string[8][3];
    static CData/*0:0*/ __Vtable66_Mlmc_Sim__DOT__area_bissc_slave_21__DOT__fsm_wantStart[8];
    static WData/*79:0*/ __Vtable67_Mlmc_Sim__DOT__area_bissc_slave_22__DOT__fsm_stateReg_string[8][3];
    static WData/*79:0*/ __Vtable68_Mlmc_Sim__DOT__area_bissc_slave_22__DOT__fsm_stateNext_string[8][3];
    static CData/*0:0*/ __Vtable69_Mlmc_Sim__DOT__area_bissc_slave_22__DOT__fsm_wantStart[8];
    static WData/*79:0*/ __Vtable70_Mlmc_Sim__DOT__area_bissc_slave_23__DOT__fsm_stateReg_string[8][3];
    static WData/*79:0*/ __Vtable71_Mlmc_Sim__DOT__area_bissc_slave_23__DOT__fsm_stateNext_string[8][3];
    static CData/*0:0*/ __Vtable72_Mlmc_Sim__DOT__area_bissc_slave_23__DOT__fsm_wantStart[8];
    
    // INTERNAL VARIABLES
    // Internals; generally not touched by application code
    VMlmc_Sim__Syms* __VlSymsp;  // Symbol table
    
    // CONSTRUCTORS
  private:
    VL_UNCOPYABLE(VMlmc_Sim);  ///< Copying not allowed
  public:
    /// Construct the model; called by application code
    /// The special name  may be used to make a wrapper with a
    /// single model invisible with respect to DPI scope names.
    VMlmc_Sim(const char* name = "TOP");
    /// Destroy the model; called (often implicitly) by application code
    ~VMlmc_Sim();
    /// Trace signals in the model; called by application code
    void trace(VerilatedVcdC* tfp, int levels, int options = 0);
    
    // API METHODS
    /// Evaluate the model.  Application must call when inputs change.
    void eval() { eval_step(); }
    /// Evaluate when calling multiple units/models per time step.
    void eval_step();
    /// Evaluate at end of a timestep for tracing, when using eval_step().
    /// Application must call after all eval() and before time changes.
    void eval_end_step() {}
    /// Simulation complete, run final blocks.  Application must call on completion.
    void final();
    
    // INTERNAL METHODS
  private:
    static void _eval_initial_loop(VMlmc_Sim__Syms* __restrict vlSymsp);
  public:
    void __Vconfigure(VMlmc_Sim__Syms* symsp, bool first);
  private:
    static QData _change_request(VMlmc_Sim__Syms* __restrict vlSymsp);
    static QData _change_request_1(VMlmc_Sim__Syms* __restrict vlSymsp);
  public:
    static void _combo__TOP__11(VMlmc_Sim__Syms* __restrict vlSymsp);
    static void _combo__TOP__26(VMlmc_Sim__Syms* __restrict vlSymsp);
    static void _combo__TOP__27(VMlmc_Sim__Syms* __restrict vlSymsp);
    static void _combo__TOP__39(VMlmc_Sim__Syms* __restrict vlSymsp);
    static void _combo__TOP__44(VMlmc_Sim__Syms* __restrict vlSymsp);
    static void _combo__TOP__45(VMlmc_Sim__Syms* __restrict vlSymsp);
    static void _combo__TOP__46(VMlmc_Sim__Syms* __restrict vlSymsp);
    static void _combo__TOP__47(VMlmc_Sim__Syms* __restrict vlSymsp);
    static void _combo__TOP__48(VMlmc_Sim__Syms* __restrict vlSymsp);
  private:
    void _ctor_var_reset() VL_ATTR_COLD;
    void _ctor_var_reset_1() VL_ATTR_COLD;
  public:
    static void _eval(VMlmc_Sim__Syms* __restrict vlSymsp);
  private:
#ifdef VL_DEBUG
    void _eval_debug_assertions();
#endif  // VL_DEBUG
  public:
    static void _eval_initial(VMlmc_Sim__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _eval_settle(VMlmc_Sim__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _initial__TOP__25(VMlmc_Sim__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _sequent__TOP__13(VMlmc_Sim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__16(VMlmc_Sim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__17(VMlmc_Sim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__18(VMlmc_Sim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__19(VMlmc_Sim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__20(VMlmc_Sim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__21(VMlmc_Sim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__22(VMlmc_Sim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__23(VMlmc_Sim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__24(VMlmc_Sim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__28(VMlmc_Sim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__29(VMlmc_Sim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__31(VMlmc_Sim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__32(VMlmc_Sim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__34(VMlmc_Sim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__35(VMlmc_Sim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__37(VMlmc_Sim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__38(VMlmc_Sim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__40(VMlmc_Sim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__41(VMlmc_Sim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__42(VMlmc_Sim__Syms* __restrict vlSymsp);
    static void _sequent__TOP__43(VMlmc_Sim__Syms* __restrict vlSymsp);
    static void _settle__TOP__1(VMlmc_Sim__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _settle__TOP__10(VMlmc_Sim__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _settle__TOP__2(VMlmc_Sim__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _settle__TOP__3(VMlmc_Sim__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _settle__TOP__4(VMlmc_Sim__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _settle__TOP__5(VMlmc_Sim__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _settle__TOP__6(VMlmc_Sim__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _settle__TOP__7(VMlmc_Sim__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _settle__TOP__8(VMlmc_Sim__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _settle__TOP__9(VMlmc_Sim__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void traceChgThis(VMlmc_Sim__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceChgThis__10(VMlmc_Sim__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceChgThis__12(VMlmc_Sim__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceChgThis__13(VMlmc_Sim__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceChgThis__14(VMlmc_Sim__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceChgThis__15(VMlmc_Sim__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceChgThis__16(VMlmc_Sim__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceChgThis__17(VMlmc_Sim__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceChgThis__18(VMlmc_Sim__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceChgThis__19(VMlmc_Sim__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceChgThis__2(VMlmc_Sim__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceChgThis__3(VMlmc_Sim__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceChgThis__4(VMlmc_Sim__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceChgThis__5(VMlmc_Sim__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceChgThis__6(VMlmc_Sim__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceChgThis__7(VMlmc_Sim__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceChgThis__9(VMlmc_Sim__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceFullThis(VMlmc_Sim__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code) VL_ATTR_COLD;
    static void traceFullThis__1(VMlmc_Sim__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code) VL_ATTR_COLD;
    static void traceFullThis__11(VMlmc_Sim__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code) VL_ATTR_COLD;
    static void traceFullThis__20(VMlmc_Sim__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code) VL_ATTR_COLD;
    static void traceFullThis__8(VMlmc_Sim__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code) VL_ATTR_COLD;
    static void traceInitThis(VMlmc_Sim__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code) VL_ATTR_COLD;
    static void traceInitThis__1(VMlmc_Sim__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code) VL_ATTR_COLD;
    static void traceInitThis__2(VMlmc_Sim__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code) VL_ATTR_COLD;
    static void traceInitThis__3(VMlmc_Sim__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code) VL_ATTR_COLD;
    static void traceInitThis__4(VMlmc_Sim__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code) VL_ATTR_COLD;
    static void traceInit(VerilatedVcd* vcdp, void* userthis, uint32_t code);
    static void traceFull(VerilatedVcd* vcdp, void* userthis, uint32_t code);
    static void traceChg(VerilatedVcd* vcdp, void* userthis, uint32_t code);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);

//----------


#endif  // guard
